### ISSUE TITLE
Name should allow other characters (not just alphanumerics and spaces)

### ISSUE THREAD

**Issue by yjskrs** [AY1920S2-CS2103T-F09-3/main#134]
Name should allow other characters (not just alphanumerics and spaces) other than anything that resembles a prefix.
![image](https://user-images.githubusercontent.com/42514097/77034552-47211880-69e5-11ea-92dc-e16dbf25b66f.png)

**Comment by nathanaelseen** [comment]
currently i checked, it allows the one you showed in the screen shot, i'll just propagate the regex you used in `Requirement Title` to `Course Name` and `Module Title` and close the issue

**Comment by nathanaelseen** [comment]
I've also made some changes to the regex to prevent the first character  from being '/' as well else fails, `requirement add t// u/4`, due to the auto requirement code generation thing wayne did
