### ISSUE TITLE
Requirement edit should catch non-existing requirement before catching missing prefixes

### ISSUE THREAD

**Issue by yjskrs** [AY1920S2-CS2103T-F09-3/main#135]
![image](https://user-images.githubusercontent.com/42514097/77034758-b7c83500-69e5-11ea-830c-a211b5a52e71.png)

**Comment by nathanaelseen** [comment]
I spent today standardising all the error messages, and just saw this.
If you wanna do it this way, have to change `module edit` too, so as to be consistent.

**Comment by nathanaelseen** [comment]
If you do this  way, you would have to contact `Model.hasRequirement/hasModule` in Model, while you're still in the `RequirementEditCommandParser` class. This design is weird cos i don't think i saw it anywhere in the original codebase. I feel its best to just leave it the way it is hmm
