### ISSUE TITLE
Course, Requirement, Module commands should show guiding error message when second word is not input

### ISSUE THREAD

**Issue by yjskrs** [AY1920S2-CS2103T-F09-3/main#139]
![image](https://user-images.githubusercontent.com/42514097/77085496-5fbc1d80-6a3b-11ea-87ff-7c6ef2e0c071.png)

**Comment by nathanaelseen** [comment]
I've just spent today doing a standardisation for this, but not exactly, what you've put here.

Only when you  type 2 words, `module add`, `module  edit`, `requirement add`, `requirement edit`, it will show some guiding message  (though its seems more like an error message) like this;
<img width="1440" alt="Screen Shot 2020-03-29 at 7 56 32 PM" src="https://user-images.githubusercontent.com/12388525/77848464-6561f200-71f7-11ea-9470-89443cad65b4.png">

**Comment by nathanaelseen** [comment]
<img width="1440" alt="Screen Shot 2020-03-30 at 3 17 00 PM" src="https://user-images.githubusercontent.com/12388525/77885416-909d1d80-7299-11ea-982f-496594f21d9a.png">

Anyway i added this feature already, i.e if the first command word (of a 2-word command; `course`, `requirement`, `module`) is valid, then it will provide a guiding message.
