### ISSUE TITLE
Duplicate module (same module code) should not be added

### ISSUE THREAD

**Issue by yjskrs** [AY1920S2-CS2103T-F09-3/main#140]
![image](https://user-images.githubusercontent.com/42514097/77086452-c68e0680-6a3c-11ea-9753-f4c6c87d848d.png)

but this one is subjective
I don't know if yall think this should be allowed or not

**Comment by nathanaelseen** [comment]
nope haha, by right should not

**Comment by nathanaelseen** [comment]
i fixed it alr btw
