### ISSUE TITLE
Grade should not be assigned immediately when adding modules with -a

### ISSUE THREAD

**Issue by yjskrs** [AY1920S2-CS2103T-F09-3/main#142]
![image](https://user-images.githubusercontent.com/42514097/77086968-72cfed00-6a3d-11ea-89a6-bbd89536d8e5.png)

Suggest that grade field be removed and replaced with a done/not done, grade field to only show when grade has been keyed in.
Or grade field to show Grade: - and updated with grade when grade has been keyed in.
or any other solutions that are better

**Comment by nathanaelseen** [comment]
yeap i've just done it in my latest PR, thanks yijie for closing!
