### ISSUE TITLE
Module assign allows module already assigned to be assigned again.

### ISSUE THREAD

**Issue by yjskrs** [AY1920S2-CS2103T-F09-3/main#298]
Response should indicate that module has already been assigned.

Steps to reproduce:
1. Assign GER1000 to GE0.
2. Assign GER1000 to GE0 again.

![image](https://user-images.githubusercontent.com/42514097/78781454-dad97980-79d2-11ea-982a-8680e04a4481.png)

**Comment by nathanaelseen** [comment]
yeah yijie, that's intended

**Comment by nathanaelseen** [comment]
should we show a list tho, of modules un/assigned?

e.g, 0 Module(s) assigned under Requirement:

**Comment by yjskrs** [comment]
still think should tell the user its already assigned though

**Comment by nathanaelseen** [comment]
ok, but here comes the tricky scenario; some modules already assigned, some aren't

**Comment by yjskrs** [comment]
tell them which are assigned and which arent ? ??

**Comment by yjskrs** [comment]
Ok if some are already assigned and the rest arent then just tell them what is newly assigned.
If all are already assigned just say all are assigned.
how bout that

**Comment by nathanaelseen** [comment]
ok

**Comment by nathanaelseen** [comment]
so i make list ah, of newly un/assigned mods?

**Comment by nathanaelseen** [comment]
(if all mods assigned already,  just say, all assigned)

**Comment by yjskrs** [comment]
unassigned one can do like
this module does not exist in the requirement, modules x y z have been unassigned

**Comment by nathanaelseen** [comment]
yeah that's true thanks

**Comment by nathanaelseen** [comment]
now just need to settle consistency of messages; 'module' or 'module code'
