### ISSUE TITLE
Requirement assign modules that do not exist in system should print less misleading message.

### ISSUE THREAD

**Issue by yjskrs** [AY1920S2-CS2103T-F09-3/main#299]
![image](https://user-images.githubusercontent.com/42514097/78781672-40c60100-79d3-11ea-80a0-a39bd41928ad.png)

**Comment by nathanaelseen** [comment]
Suggestions please, i'm bad at this lol

**Comment by yjskrs** [comment]
Module(s) do not exist in system. Please key in modules that exist (?)

You could probably also do it like the assigning modules that are alr assigned to req, allow modules that exist to be assigned then telling user the modules that dont exist 

If im making sense

**Comment by nathanaelseen** [comment]
oh hmm, should we allow that

**Comment by nathanaelseen** [comment]
ok yeap, makes sense to allow, since wayne's auto module add does that too (notifying users if module can't be found in NUSMods API)

**Comment by nathanaelseen** [comment]
This again is inconsistent;
`Module(s) do not exist in system. Please key in modules that exist (?)`,
 with
`public static final String MESSAGE_REQUIREMENT_NON_EXISTENT = "The requirement code provided is invalid.";` (in RequirementCommand.java)

**Comment by nathanaelseen** [comment]
choose one pls

**Comment by nathanaelseen** [comment]
`Module(s) do not exist in system. Please key in modules that exist (?)`
vs
`The module code(s) provided is invalid. Please key in module code(s) that is valid`

**Comment by yjskrs** [comment]
whats the deal with the requirementCommand constant? its telling you about requirement code

**Comment by yjskrs** [comment]
> `Module(s) do not exist in system. Please key in modules that exist (?)`
> vs
> `The module code(s) provided is invalid. Please key in module code(s) that is valid`

Are you telling me to choose one of them or what :eyes:

**Comment by nathanaelseen** [comment]
yeah since you were the one who standardised this messages

**Comment by nathanaelseen** [comment]
and your requirement edit used 'requirement code' for non-existent requirement, so for non-existent modules should i use 'module code(s)', as well, instead of 'module(s)'

**Comment by yjskrs** [comment]
i dont think thats important.... but i guess we can choose one.....

both is fine idk can ask the group

**Comment by nathanaelseen** [comment]
no cos if you choose one, you've to standardise the rest

**Comment by nathanaelseen** [comment]
like module edit, etc

**Comment by nathanaelseen** [comment]
i'll just stick with 'modules' first then
