### ISSUE TITLE
As a student, I want to be able to export the data to an excel sheet in case I need to submit a study plan (e.g. for exchange).

### ISSUE THREAD

**Issue by waynewee** [AY1920S2-CS2103T-F09-3/main#55]

**Comment by nathanaelseen** [comment]
this is a cool feature too hmm, but exporting data to **excel**  could be  complicated due to the specific XML structure to do so, we might need an external library for that!

**Comment by waynewee** [comment]
can write CSV file without external libraries. Ill do this
