### ISSUE TITLE
Integrate requirement class (stubs) into code-base

### ISSUE THREAD

**Issue by waynewee** [AY1920S2-CS2103T-F09-3/main#87]

**Comment by yjskrs** [comment]
Er @nathanaelseen why you close

**Comment by nathanaelseen** [comment]
sry I was confused, I thought this was a duplicate of this issue; `Support Requirement Commands (add, modify, delete) #91`, so I closed it

**Comment by nathanaelseen** [comment]
@yjskrs could you rename this, I don't understand this task

**Comment by yjskrs** [comment]
I'm just making a class without adding the commands and methods

**Comment by nathanaelseen** [comment]
ok can, I'll just rename to 'Integrate requirement class (stubs) into code-base'

**Comment by nathanaelseen** [comment]
I'll close this when I've finished merging the PR, sry for the delays!
